module.exports = {
  mode: "jit",
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        // anime: "url('https://wallpapercave.com/dwp1x/wp8297346.jpg')",
        // anime: "url('https://i.imgur.com/a9Ueu8U.png')",
        // anime: "url('https://i.imgur.com/x2UAb0g.png')",
        anime: "url('https://i.imgur.com/7ovGzk7.png')",
        chibi1: "url('https://i.imgur.com/mOsVNiB.jpg')",
        chibi2: "url('https://i.imgur.com/enDvxbj.jpg')",
        chibi3: "url('https://i.imgur.com/Lu7K6Ii.jpg')",
        // "footer-texture": "url('/img/footer-texture.png')",
      },
      spacing: {
        104: "26rem",
        112: "28rem",
        120: "30rem",
        128: "32rem",
        136: "34rem",
        144: "36rem",
        152: "38rem",
        160: "40rem",
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "cupcake",
      "light",
      "dark",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
    darkTheme: "cupcake",
  },
};
