export const BOOKS_LIST_REQUEST = "BOOKS_LIST_REQUEST";
export const BOOKS_LIST_SUCCESS = "BOOKS_LIST_SUCCESS";
export const BOOKS_LIST_FAIL = "BOOKS_LIST_FAIL";
export const BOOKS_REMOVEALL_SUCCESS = "BOOKS_REMOVEALL_SUCCESS";

export const BOOKS_CREATE_REQUEST = "BOOKS_CREATE_REQUEST";
export const BOOKS_CREATE_SUCCESS = "BOOKS_CREATE_SUCCESS";
export const BOOKS_CREATE_FAIL = "BOOKS_CREATE_FAIL";

export const BOOKS_UPDATE_REQUEST = "BOOKS_UPDATE_REQUEST";
export const BOOKS_UPDATE_SUCCESS = "BOOKS_UPDATE_SUCCESS";
export const BOOKS_UPDATE_FAIL = "BOOKS_UPDATE_FAIL";

export const BOOKS_DELETE_REQUEST = "BOOKS_DELETE_REQUEST";
export const BOOKS_DELETE_SUCCESS = "BOOKS_DELETE_SUCCESS";
export const BOOKS_DELETE_FAIL = "BOOKS_DELETE_FAIL";
