import Head from "next/head";
import { Toaster } from "react-hot-toast";
import LoadingBar from "react-redux-loading-bar";
import { Provider } from "react-redux";

import "../styles/globals.css";
import store from "../src/store";
import Navbar from "../src/components/Navbar";
import MyModals from "../src/components/MyModals";
import Footer from "../src/components/Footer";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>BooksWagon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="BooksWagon Clone" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={store}>
        <LoadingBar
          style={{
            backgroundColor: "hsl(var(--p))",
            zIndex: "50",
            height: "4px",
          }}
          showFastActions
        />

        <Toaster />

        <div class="bg-base-100 drawer">
          <input id="my-drawer" type="checkbox" class="drawer-toggle" />
          <div
            class="drawer-content overflow-x-hidden min-w-full"
            style={{ scrollBehavior: "smooth" }}
          >
            {/* <!-- Page content here --> */}
            <Navbar />
            <Component {...pageProps} />
            <Footer />
          </div>
          <div class="drawer-side">
            <label for="my-drawer" class="drawer-overlay"></label>
            <ul class="menu p-4 overflow-y-auto w-80 bg-base-200 text-base-content">
              {/* <!-- Sidebar content here --> */}
              <li tabIndex="0" class="dropdown dropdown-hover dropdown-left">
                <a>
                  Books
                  <svg
                    class="fill-current"
                    xmlns="http://www.w3.org/2000/svg"
                    width="20"
                    height="20"
                    viewBox="0 0 24 24"
                  >
                    <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                  </svg>
                </a>
                <ul class="p-2 bg-base-100 z-30 dropdown-content">
                  <li>
                    <a>Arts and Photography</a>
                  </li>
                  <li>
                    <a>Biography and Memoirs</a>
                  </li>
                  <li>
                    <a>Dictionaries and Language</a>
                  </li>

                  <li>
                    <a>Literature and Literary Studies</a>
                  </li>
                  <li>
                    <a>English Language and Teaching</a>
                  </li>
                  <li>
                    <a>Fiction</a>
                  </li>
                </ul>
              </li>
              <li>
                <a>New Arrivals</a>
              </li>
              <li class="menu-title">
                <span>Category 1</span>
              </li>
              <li>
                <a>Box Sets</a>
              </li>
              <li>
                <a>Best Sellers</a>
              </li>
              <li class="menu-title">
                <span>Category 2</span>
              </li>
              <li>
                <a>Fictional Books</a>
              </li>
              <li>
                <a>Award Winners</a>
              </li>
              <li>
                <a>Featured Authors</a>
              </li>
            </ul>
          </div>
        </div>

        <MyModals />
      </Provider>
    </>
  );
}

export default MyApp;
